# Generated by Django 3.2.3 on 2021-06-01 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mainpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(default='none', max_length=10)),
                ('position', models.CharField(choices=[('position', 'officer'), ('position', 'member')], default='none', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sstrength', models.CharField(max_length=500, null=True)),
                ('Sweak', models.CharField(max_length=500, null=True)),
                ('SSuggestion', models.CharField(max_length=500, null=True)),
                ('SFeedback', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, null=True)),
                ('middle', models.CharField(max_length=500, null=True)),
                ('surname', models.CharField(max_length=500, null=True)),
                ('course', models.CharField(max_length=500, null=True)),
                ('section', models.CharField(max_length=500, null=True)),
                ('number', models.CharField(max_length=500, null=True)),
                ('email', models.TextField(max_length=500, null=True)),
                ('position', models.CharField(max_length=500, null=True)),
                ('gender', models.CharField(choices=[('male', 'gender'), ('female', 'gender'), ('others', 'gender')], default='none', max_length=10)),
                ('today', models.DateTimeField(null=True)),
                ('Officer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='edlist.mainpage')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname2', models.CharField(max_length=50, null=True)),
                ('middle2', models.CharField(max_length=10, null=True)),
                ('surname2', models.CharField(max_length=50, null=True)),
                ('course2', models.CharField(max_length=100, null=True)),
                ('section2', models.CharField(max_length=100, null=True)),
                ('email2', models.TextField(max_length=100, null=True)),
                ('number2', models.CharField(max_length=100, null=True)),
                ('gender2', models.CharField(choices=[('male', 'gender'), ('female', 'gender'), ('others', 'gender')], default='none', max_length=10)),
                ('today2', models.DateTimeField(null=True)),
                ('Member', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='edlist.mainpage')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees', models.CharField(max_length=300, null=True)),
                ('display', models.CharField(max_length=100, null=True)),
                ('Contribution2', models.ManyToManyField(to='edlist.Mainpage')),
            ],
        ),
        migrations.CreateModel(
            name='Contribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('Contribution', models.ManyToManyField(to='edlist.Mainpage')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitiesDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adate', models.DateTimeField(null=True)),
                ('ASuggestion', models.CharField(max_length=100, null=True)),
                ('AComments', models.CharField(max_length=100, null=True)),
                ('ActivitiesDisplay1', models.ManyToManyField(to='edlist.Mainpage')),
            ],
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adviser', models.CharField(max_length=300, null=True)),
                ('Aone', models.CharField(max_length=100, null=True)),
                ('Atwo', models.CharField(max_length=100, null=True)),
                ('Athree', models.CharField(max_length=100, null=True)),
                ('Afour', models.CharField(max_length=100, null=True)),
                ('Afive', models.CharField(max_length=100, null=True)),
                ('Activities1', models.ManyToManyField(to='edlist.Mainpage')),
            ],
        ),
    ]
