# Generated by Django 3.2.3 on 2021-06-10 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Poposed_Date', models.DateField()),
                ('Description_Activities', models.CharField(default='', max_length=50)),
                ('name_proposed_activities', models.CharField(default='', max_length=20)),
                ('target_paticipant', models.CharField(default='', max_length=20)),
                ('paticipant_number', models.IntegerField(default=0, max_length=20)),
                ('estimated_Budget', models.IntegerField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MemberDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_name', models.CharField(default='', max_length=20)),
                ('M_course_section', models.CharField(default='', max_length=50)),
                ('M_emailaddress', models.EmailField(default='', max_length=50)),
                ('M_studentIDnumber', models.CharField(default='', max_length=20)),
                ('gender_member', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('course_section', models.CharField(default='', max_length=50)),
                ('gender_officer', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('emailaddress', models.EmailField(default='', max_length=50)),
                ('studentIDnumber', models.CharField(default='', max_length=20)),
                ('position', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='', max_length=30)),
                ('academic_year', models.CharField(default='', max_length=20)),
                ('adviser', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReportDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(default='', max_length=100)),
                ('Evaluation_Report', models.TextField(default='', max_length=100)),
                ('Description', models.TextField(default='', max_length=100)),
                ('Report', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='edlist.activitiesdetails')),
            ],
        ),
        migrations.RemoveField(
            model_name='activities',
            name='Activities1',
        ),
        migrations.RemoveField(
            model_name='activitiesdisplay',
            name='ActivitiesDisplay1',
        ),
        migrations.RemoveField(
            model_name='contribute',
            name='Contribution',
        ),
        migrations.RemoveField(
            model_name='contribution2',
            name='Contribution2',
        ),
        migrations.RemoveField(
            model_name='member',
            name='Member',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='Officer',
        ),
        migrations.DeleteModel(
            name='survey',
        ),
        migrations.DeleteModel(
            name='Activities',
        ),
        migrations.DeleteModel(
            name='ActivitiesDisplay',
        ),
        migrations.DeleteModel(
            name='Contribute',
        ),
        migrations.DeleteModel(
            name='Contribution2',
        ),
        migrations.DeleteModel(
            name='Mainpage',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Officer',
        ),
        migrations.AddField(
            model_name='officerdetails',
            name='officer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='edlist.organization'),
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='Member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='edlist.organization'),
        ),
        migrations.AddField(
            model_name='activitiesdetails',
            name='Activities',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='edlist.officerdetails'),
        ),
    ]
