# Generated by Django 3.1.6 on 2021-04-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='org',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='batch',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
