# Generated by Django 3.2.3 on 2021-06-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edlist', '0002_auto_20210610_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesdetails',
            name='estimated_Budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activitiesdetails',
            name='paticipant_number',
            field=models.IntegerField(default=0),
        ),
    ]
