# Generated by Django 3.1.6 on 2021-04-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edlist', '0002_auto_20210423_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='today',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
