# Generated by Django 3.1.6 on 2021-04-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edlist', '0005_auto_20210424_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date',
            new_name='today',
        ),
    ]
