# Generated by Django 3.1.6 on 2021-04-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edlist', '0007_auto_20210425_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='suggest',
        ),
        migrations.AddField(
            model_name='item',
            name='tion',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='concern',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
