# Generated by Django 3.1.6 on 2021-04-25 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edlist', '0008_auto_20210425_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='concern',
            new_name='cern',
        ),
    ]
