# Generated by Django 3.1.6 on 2021-04-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edlist', '0009_auto_20210425_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cern',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tion',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
