# Generated by Django 3.1.6 on 2021-04-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edlist', '0010_auto_20210425_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(choices=[('male', 'gender'), ('female', 'gender')], default='none', max_length=10),
        ),
    ]
